### PR TITLE
add ci

### PR DESCRIPTION
**Pull request by NamorNiradnug**

### CODE REVIEW

**Comment by ammen99** [comment]
Great idea. I assume you'd need to update the formatting in most files, however.

**Review by ammen99 — APPROVED** [review]

**Comment by NamorNiradnug** [comment]
I appreciate the amount of braces...

**Comment by ammen99** [comment]
> I appreciate the amount of braces...

Hehe ;) At least now the code looks consistently formatted if nothing else ..

**Review by ammen99 — APPROVED** [review]
Thanks!

**Comment by ammen99** [comment]
Well, unfortunately needs a few more dependencies: https://github.com/WayfireWM/wf-shell/actions/runs/5743677900/job/15568467944

Also code apparently isn't formatted enough .. Uncrustify is weird sometimes, you have to run it multiple times until it stabilizes: https://github.com/WayfireWM/wf-shell/actions/runs/5743677900/job/15568468169

**Pull request merged**
