### PR TITLE
panel: Implement default logout user interface

### PR DESCRIPTION
**Pull request by soreau**
When a user clicks the logout button in the menu and no command is set,
open a default logout interface.

### CODE REVIEW

**Comment by soreau** [comment]
screenshot

**Comment by ammen99** [comment]
The idea looks good. However: should we not present the window as a layer-shell overlay on top of everything? I think this is the default in other DEs, but please correct me if I'm wrong.

**Comment by soreau** [comment]
> The idea looks good. However: should we not present the window as a layer-shell overlay on top of everything? I think this is the default in other DEs, but please correct me if I'm wrong.

The way it is currently, the logout UI can be minimized or closed and other views can occlude it, and it calls `gtk-window-present` to unminimize and/or raise the view if it the logout button is clicked again. This is perfectly sane behavior to me. What are the benefits to having it a layer-shell always-on-top view that differ from this behavior?

**Review by ammen99 — APPROVED** [review]
Looks cool, thanks!

**Pull request merged**
