### PR TITLE
window-list: attach popup menu to button

### PR DESCRIPTION
**Pull request by trigg**

### CODE REVIEW

**Comment by trigg** [comment]
Aligns edge of popup to edge of the button, orientation is corrected by Gtk by default if top/bottom is selected

**Comment by ammen99** [comment]
So this changes the position of the menu popup, a question at people who use this menu (@soreau? and probably others) which one do you prefer:

- New layout:
slurped

- Old layout:
slurped


I.e should the menu be centered on where the user clicked (which is somewhere in the middle of the button) or below the button.

**Comment by trigg** [comment]
And one with a bit more space on the list

**Comment by trigg** [comment]
For reference, I feel this is correct as it matches clock, menu & (more recently) tray.

**Comment by ammen99** [comment]
Thanks!

**Pull request merged**
