### PR TITLE
window-list: use ~/.local/share when looking for apps / icons

### PR DESCRIPTION
**Pull request by lcolitti**
The icons in the window list are loaded by parsing the desktop files for a few variations of the window's app ID in a few known locations.

Add /.local/share/applications to the list of locations it looks in, to ensure that apps installed in the user's home directory are considered as well.

### CODE REVIEW

**Comment by soreau** [comment]
Somehow I'm thinking this should rely on XDG_DATA_DIRS to do the right thing. Consider Gio::DesktopAppInfo::create() [here](https://developer-old.gnome.org/glibmm/stable/classGio_1_1DesktopAppInfo.html).

**Comment by ammen99** [comment]
I think @soreau is right, probably if we try the create() method first, we would most likely be able to cover this case and even a few others.

**Comment by lcolitti** [comment]
> Somehow I'm thinking this should rely on XDG_DATA_DIRS to do the right thing. Consider Gio::DesktopAppInfo::create() [here](https://developer-old.gnome.org/glibmm/stable/classGio_1_1DesktopAppInfo.html).

Ah yes, that looks much better. Thanks for the suggestion!

**Comment by lcolitti** [comment]
Looks like the CI tests are broken for unrelated reasons:

```
  Error relocating /usr/lib/libcurl.so.4: SSL_get0_group_name: symbol not found
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by ammen99** [comment]
@lcolitti You can probably use `alpine:latest` instead of `alpine:edge`

**Comment by lcolitti** [comment]
> @lcolitti We can probably use `alpine:latest` instead of `alpine:edge` to make the CI work again

Yup, definitely looks happier after changing that.

**Comment by soreau** [comment]
Bonus points for removing more lines than added. 👍

**Pull request merged**
