### PR TITLE
panel: stringify network_ and battery_status

### PR DESCRIPTION
**Pull request by NamorNiradnug**
This makes config files more readable.

### CODE REVIEW

**Comment by NamorNiradnug** [comment]
By the way, I've noticed that displaying IP is not implemented, so maybe the corresponding option should be removed, at least until it's implemented?

Tbh, I'm not sure if this is a really useful feature, but I think I could implement this if you think otherwise.

**Comment by ammen99** [comment]
@NamorNiradnug Feel free to remove any unused code or unsupported values :)

**Comment by soreau** [comment]
Not related to this PR, but wf-background doesn't use [this variable](https://github.com/WayfireWM/wf-shell/blob/master/src/background/background.hpp#L44) though it's set [here](https://github.com/WayfireWM/wf-shell/blob/master/src/background/background.cpp#L286).

**Review by ammen99 — APPROVED** [review]
I don't like breaking changes but the current interface is indeed very confusing, so LGTM.

Thanks!

**Pull request merged**
