### PR TITLE
Update to latest foreign toplevel protocol

### PR DESCRIPTION
**Pull request by soreau**

### CODE REVIEW

**Comment by ammen99** [comment]
Do you plan on adding any functionality depending on these new versions? Otherwise there doesn't seem to be a need to update the version.

**Comment by ammen99** [comment]
I suppose for example we could hide the toplevels which have their parent set.

**Comment by soreau** [comment]
> I suppose for example we could hide the toplevels which have their parent set.

I implemented this in the latest push.

**Comment by ammen99** [comment]
Closing this, I suppose we can just merge #70 because it is basically this PR + fixes

**Pull request closed without merging**
